baseURL = "https://www.mompreneursuccessacademy.com/"
languageCode = "en-us"
summaryLength = 20
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
