baseURL = "https://www.mompreneursuccessacademy.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 20
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 7
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
