baseURL = "https://mompreneursuccessacademy.netlify.app/"
languageCode = "en-us"
summaryLength = 20
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
