baseURL = "https://mompreneursuccessacademy.netlify.app/"
languageCode = "en-us"
summaryLength = 20
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Virtual Field Trips"
url = "/"
weight = 2
[[menu.main]]
name = "Success Academy"
url = "/"
weight = 3
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5